---
- name: Deploy Dino Dash backend - User Management
  hosts: app
  vars:
    non_prod_namespace: dino-dash-non-prod
    prod_namespace: dino-dash-prod
  tasks:
  - include_vars: "{{ inventory_dir }}/../encrypted-vars.yml"
  - include_role:
      name: openshift-applier/roles/openshift-applier
  - name: Set maven slave image
    shell: oc set env dc jenkins MAVEN_SLAVE_IMAGE=quay.io/camedeir/jenkins-agent-quarkus:latest -n "{{ non_prod_namespace }}"
